training_indra/config/routes.rb
TrainingIndra::Application.routes.draw do
  resources :articles, :users, :countries, :users, :products, :comments, :sessions
  root :to => 'articles#index'
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  namespace :admin do
   resources :articles
  end
  
  

end

training_indra/app/models/article.rb
class Article < ActiveRecord::Base
   attr_accessible :title, :text
   has_many :comments, :dependent=> :destroy 
   belongs_to :users
   scope :artikel, lambda {|articles| where("rating = ?", artikel) }
   #Validation
   validates :title,  :presence => {:message=>"you must be filled username"},
                      :uniqueness => true

   #validate :validtitle
   validates :title,  :presence => {:message=>"you must be filled username"}

   def validtitle
    self.errors[:title] << "can't filled by 'blank'/'empty'/'null'" if title == 'blank' or 'empty' or 'null'
   end  
                      
   
   def self.show_all_article
    where("length(text) <= 100")
   end

end

training_indra/app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  protect_from_forgery
  def require_admin_login
     if current_user.nil? || !current_user.is_admin?
       flash[:error] = "Only admins are permitted"
       redirect_to log_in_path
    else
       return current_user
    end
  end
  before_filter :require_admin_login
  rescue_from NoMethodError, :with => :record_not_found

  private
   def record_not_found
    render "/public/500.html", :status => 500, :layout => false
  end

end

training_indra/app/controllers/article_controller.rb
class ArticleController < ApplicationController
 def index
 end
end

training_indra/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index    
    @article = Article.all
    @lastarticle = Article.maximum(:id)
    @lastarticle = Article.find(@lastarticle)
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
     flash[:delete] = "You was delete 1 article"
     redirect_to :action => :index
    end

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
      @article = Article.find(params[:id]) 
      if @article.update_attributes(params[:article])
         flash[:update] = "You was update 1 article"
         redirect_to :action => :index
      else
       render :action => 'edit'
      end

    end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "You was add 1 article"
      redirect_to :action=>'index'
    else
      render :action=>'new'
    end

  end
 
  before_filter :require_login, :only => [:new, :create, :edit, :update, :delete]
  
end

training_indra/app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

training_indra/app/helpers/article_helper.rb
module ArticleHelper
end

training_indra/app/helpers/articles_helper.rb
module ArticlesHelper
  
end

training_indra/app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.full_messages.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    <% end %>
    </ul>
  </div>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit :create%>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>
 

training_indra/app/views/articles/show.html.erb
<!--This section is to show all comments that owned by the article  -->
<div id="comments">
  <% @comments.each do |comment| %>
    <%= comment.content %><br />
  <% end %>
</div><br /><br />


<% unless(current_user.nil?)%>
   <%= form_for @comment, :url => comments_path do |f| -%>
      <%= f.text_area :content %>
      <%= f.hidden_field :article_id, :value => @article.id %>
      <%= submit_tag "comment" %>
  <% end -%>
<% end %>