training_indra/config/routes.rb
TrainingIndra::Application.routes.draw do
  resources :articles, :users, :countries, :users, :products, :comments, :sessions
  root :to => 'articles#index'
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"  
  get "log_out" => "sessions#destroy", :as => "log_out"
  namespace :admin do
   resources :articles
  end
  
  

end

training_indra/app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :code, :name
  has_many :users
  has_many :products
  has_many :national,
           :class_name => "User" ,
           :foreign_key => "countries_id" ,
           :conditions => "countries_id = '1'"
 
  #Validation
  #type_regex = /(usa)|(idn)|(chn)/
  #validates :code,  :presence => {:message=>"you must be filled username"},
   #                 :format => {:with => type_regex}
  #validates :name,  :presence => {:message=>"you must be filled username"}
end

training_indra/app/controllers/countries_controller.rb
class CountriesController < ApplicationController

  def index    
    @country = Country.all  
    @lastcountry = Country.maximum(:id)
    @lastcountry = Country.find(@lastcountry)
  end

  def destroy
    @country = Country.find(params[:id])
    if @country.destroy
     flash[:delete] = "You was delete 1 country"
     redirect_to :action => :index
    end
  end

  def edit
    @country = Country.find(params[:id])
  end

  def update
    
    @country = Country.find(params[:id]) 
    if @country.update_attributes(params[:Country])
      if @product.save
       flash[:notice] = "You was update 1 country"
       redirect_to :action => :index
      end
      else
        render :action => 'edit'
      end

    end

  def show
    if @country = Country.find(params[:id])
      render :action=>'show'
    else
      redirect_to country_path
    end
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(params[:Country])
    if @country.save
      redirect_to :action => :index
      flash[:notice] = "You was succesfully create 1 country"
    else
      render :action => 'new'
    end

  end
end

training_indra/app/helpers/countries_helper.rb
module CountriesHelper
end

training_indra/app/views/countries/new.html.erb
<%= form_for @country do |f| %>
  
  <div id="error_explanation">
    <h2><%= pluralize(@country.errors.count, "error") %> prohibited
      this country from being saved:</h2>
    <ul>
    <% @country.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <p>
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </p>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </p>
 
  <p>
    <%= f.submit :create%>
  </p>
<% end %>

<%= link_to 'Back', articles_path %>
 

training_indra/app/views/countries/show.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>

  <tr>
    <td><%= @country.code %></td>
    <td><%= @country.name %></td>
    <td><%= link_to 'Edit', edit_country_path(@country) %></td>
    <td><%= link_to "Delete", country_path(@country), :confirm => "Are you sure?", :method=>:delete %></td>
  </tr>
  <td><%= link_to 'Back', countries_path %></td>
</table>